name: CICD Pipeline 

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn compile

  security-check:
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - uses: actions/checkout@v4
      - name: Run Trivy FS Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'table'
          output: 'trivy-report.json'
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

  test:
    runs-on: ubuntu-latest
    needs: security-check
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Unit Test Cases
        run: mvn test

  build_project:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build Project
        run: mvn package
      # SonarQube ko abhi skip kar rahe hain jab tak aapke paas credentials na ho
      # Taaki aapka aage ka deployment flow test ho sake

  build-and-push:
    runs-on: ubuntu-latest
    needs: build_project
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USER }}/bankapp:${{ github.run_id }} .
          docker push ${{ secrets.DOCKER_USER }}/bankapp:${{ github.run_id }}
          docker tag ${{ secrets.DOCKER_USER }}/bankapp:${{ github.run_id }} ${{ secrets.DOCKER_USER }}/bankapp:latest
          docker push ${{ secrets.DOCKER_USER }}/bankapp:latest

      - name: Update Manifest for ArgoCD (GitOps)
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          # ds.yml mein image update logic
          sed -i "s|image: ${{ secrets.DOCKER_USER }}/bankapp:.*|image: ${{ secrets.DOCKER_USER }}/bankapp:${{ github.run_id }}|g" ds.yml
          git add ds.yml
          git commit -m "chore: update image tag to ${{ github.run_id }} [skip ci]"
          git push
